workflows:
  android-build:
    name: Android Build
    instance_type: linux_x2
    max_build_duration: 120
    environment:
      node: 18
      java: 11
      groups:
        - expo_credentials
    scripts:
      - name: Install dependencies
        script: |
          npm install -g eas-cli
          pnpm install
      - name: Build Android APK
        script: |
          eas build --platform android --profile preview --non-interactive
    artifacts:
      - build/**/*.apk
