/**
 * BUNDLED BRAND MARKS, wiring. Source reading; the behaviour (which names
 * match, ground contrast, tile selection) is in brand-marks.test.ts, which
 * needs the real runner because it imports TypeScript.
 *
 * Until 2026-10-06 components/LogoImage.tsx loaded logo.clearbit.com, which
 * HubSpot shut down in December 2025. Every request failed, so every logo in
 * the app was a category icon and nothing said so. These pin that the app no
 * longer depends on a third party for a logo, and that it stays OTA safe.
 */
const fs = require('fs');
const path = require('path');

const root = path.join(__dirname, '..');
const read = (p) => fs.readFileSync(path.join(root, p), 'utf8');
const readNew = (p) => (fs.existsSync(path.join(root, p)) ? read(p) : '');
const codeOf = (s) => s.replace(/\/\*[\s\S]*?\*\//g, '');

const LOGO = codeOf(read('components/LogoImage.tsx'));
const DATA = readNew('lib/brand-mark-data.ts');
const GEN = readNew('tools/build-brand-marks.js');
const CARD = read('components/FirstRunCard.tsx');
const SUBS = read('app/(tabs)/subscriptions.tsx');
const PKG = JSON.parse(read('package.json'));

describe('logos are bundled, not fetched', () => {
  it('LogoImage requests nothing over the network', () => {
    expect(LOGO).not.toMatch(/https?:\/\//);
    expect(LOGO).not.toMatch(/<Image\b/);
    expect(LOGO).not.toContain('clearbit');
  });

  it('a service with no mark gets its letter, at a fixed size, before any category icon', () => {
    expect(LOGO).toContain('const letter = monogramFor(name);');
    expect(LOGO).toMatch(/<Text allowFontScaling=\{false\}/);
    expect(LOGO.indexOf('monogramFor(name)')).toBeLessThan(LOGO.indexOf('getCategoryIcon(category)'));
  });

  it('the monogram helper uses no Unicode property escape Hermes might not parse', () => {
    expect(codeOf(read('lib/brand-marks.ts'))).not.toMatch(/\\p\{/);
  });

  it('LogoImage draws the bundled mark and keeps the category fallback', () => {
    expect(LOGO).toContain('from "react-native-svg"');
    expect(LOGO).toContain('brandMarkFor(name)');
    expect(LOGO).toMatch(/<Path d=\{mark\.path\} fill=\{mark\.hex\} \/>/);
    expect(LOGO).toContain('getCategoryIcon(category)');
  });

  it('react-native-svg is already a native dependency, so this ships over the air', () => {
    // It has been in package.json since 2026-07-21 and DonutChart uses it, so
    // build 40 carries it. Removing it would make every mark a native crash.
    expect(PKG.dependencies['react-native-svg']).toBeTruthy();
    expect(read('components/DonutChart.tsx')).toContain('react-native-svg');
  });
});

describe('the data is generated, and the generator holds its own guards', () => {
  it('the data file says where it came from and is not hand edited', () => {
    expect(DATA).toMatch(/^\/\* GENERATED by tools\/build-brand-marks\.js from simple-icons \d+\.\d+\.\d+/);
  });

  it('the generator refuses illegible wordmarks and illegible colours', () => {
    expect(GEN).toContain('const MAX_ASPECT = 2.5;');
    expect(GEN).toMatch(/if \(aspect > MAX_ASPECT\)/);
    expect(GEN).toMatch(/ratio\(hex, WHITE\) >= 3 \? WHITE : NAVY/);
    expect(GEN).toMatch(/if \(ratio\(hex, ground\) < 3\)/);
  });

  it('every generated row carries the six fields LogoImage reads', () => {
    const rows = DATA.split('\n').filter((l) => l.startsWith('  {')).map((l) => JSON.parse(l.trim().replace(/,$/, '')));
    expect(rows.length).toBeGreaterThan(30);
    for (const r of rows) expect(Object.keys(r).sort()).toEqual(['ground', 'hex', 'match', 'path', 'slug', 'title']);
  });
});

describe('tiles lead with marks from the reader\'s own catalogue', () => {
  it('the first-run card', () => {
    expect(CARD).toContain('getRegionalPopularTemplates(preferDach)');
    expect(CARD).toMatch(/marksFirst\(sameCurrency\.length >= TILE_COUNT \? sameCurrency : popular\)\.slice\(0, TILE_COUNT\)/);
    expect(codeOf(CARD)).not.toContain('tpl.domain');
  });

  it('the add form quick picks', () => {
    expect(SUBS).toContain('marksFirst(getRegionalPopularTemplates(preferDach)).slice(0, 8)');
    expect(SUBS).not.toContain('tpl.domain');
  });
});
